pipeline:
  build:
    image: nrc/centos67-python-node:latest
    pull: true
    commands:
      - yum install -y http://centos6.iuscommunity.org/ius-release.rpm
      - yum install -y git-core python27 python27-libs python27-pip python27-virtualenv
      - yum install -y libjpeg-turbo-devel libpng-devel libcurl-devel gcc gcc-c++
      - make venv
      - make package

  s3:
    image: plugins/s3
    bucket: nrcbuilds
    acl: private
    region: eu-west-1
    secrets: [ AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY ]
    source: builds/${DRONE_COMMIT_SHA}.tar.gz
    target: github.com/nrcmedia/thumbor/${DRONE_COMMIT_BRANCH}
    strip_prefix: builds/
    when:
      owner: nrcmedia
      event: [push, tag, deployment]
